CREATE TABLE PRODUTOS (
    NOME VARCHAR,
    PRECO DECIMAL,
    DESCRICAO VARCHAR,
    URL_FOTO VARCHAR,
    ID INTEGER PRIMARY KEY
);

CREATE TABLE CONFEITARIA (
    ID INTEGER PRIMARY KEY,
    NOME VARCHAR,
    ENDERECO VARCHAR,
    DESCRICAO VARCHAR,
    TELEFONE_ VARCHAR,
    CELULAR VARCHAR,
    CNPJ_CPF VARCHAR
);

CREATE TABLE CATEGORIA (
    ID INTEGER PRIMARY KEY,
    NOME VARCHAR
);

CREATE TABLE PRODUTO_CATEGORIA (
    FK_PRODUTOS_ID INTEGER,
    FK_CATEGORIA_ID INTEGER
);

CREATE TABLE CUSTOM (
    URL_LOGO VARCHAR,
    COR_PRIMARIA VARCHAR,
    COR_SECUNDARIA  VARCHAR,
    COR_HEADER/FOOTER VARCHAR,
    ID INTEGER PRIMARY KEY
);

CREATE TABLE CADASTRO (
    ID INTEGER PRIMARY KEY,
    SENHA VARCHAR,
    EMAIL VARCHAR
);

CREATE TABLE CONFEITARIA_PRODUTOS  (
    FK_PRODUTOS_ID INTEGER,
    FK_CONFEITARIA_ID INTEGER
);
 
ALTER TABLE PRODUTO_CATEGORIA ADD CONSTRAINT FK_PRODUTO_CATEGORIA_1
    FOREIGN KEY (FK_PRODUTOS_ID)
    REFERENCES PRODUTOS (ID)
    ON DELETE RESTRICT;
 
ALTER TABLE PRODUTO_CATEGORIA ADD CONSTRAINT FK_PRODUTO_CATEGORIA_2
    FOREIGN KEY (FK_CATEGORIA_ID)
    REFERENCES CATEGORIA (ID)
    ON DELETE SET NULL;
 
ALTER TABLE CONFEITARIA_PRODUTOS  ADD CONSTRAINT FK_CONFEITARIA_PRODUTOS _1
    FOREIGN KEY (FK_PRODUTOS_ID???, FK_CONFEITARIA_ID???)
    REFERENCES ??? (???);
